### ISSUE TITLE
Status/need help?

### ISSUE THREAD

**Issue by gerbyzation** [pycasbin/django-orm-adapter#1]
Hi,

This looks great, we're looking to adopt this for our project. Wondering what the status of this is? Anything you need help with?

Best,
Gerben

**Comment by gerbyzation** [comment]
I've done some work necessary to be able to use it in our django app.
You can find my work in this fork: https://github.com/actioncy/django-orm-adapter/

It works like a normal django app, so dropping it in `INSTALLED_APPS` and running migrate is enough to get it going. It supports autosave functionality. There are some things to get done to get it ready for publishing, but let me know if you'd be open to a PR

**Comment by hsluoyz** [comment]
Hi @gerbyzation sorry for the late response. Can you make a PR from your code?

**Comment by gerbyzation** [comment]
@hsluoyz done!

I've also run into the problem where several instances don't sync because I didn't realise watchers are needed for that, so exploring if this can be done using postgres listen/notify. Any thoughts on this?

**Comment by hsluoyz** [comment]
@gerbyzation thanks for your PR! https://github.com/pycasbin/django-orm-adapter/pull/2

> I've also run into the problem where several instances don't sync because I didn't realise watchers are needed for that, so exploring if this can be done using postgres listen/notify. Any thoughts on this?

Is this a new issue? If yes, you can open a new GitHub issue, so we can easily track its progress :)

**Comment by hsluoyz** [comment]
Merged: https://github.com/pycasbin/django-orm-adapter/pull/2
