### ISSUE TITLE
Replace Travis CI with GitHub Actions and setup semantic-release

### ISSUE THREAD

**Issue by hsluoyz** [pycasbin/django-orm-adapter#12]
Refer to:

https://github.com/pycasbin/sqlalchemy-adapter/commit/60b3253cfadc63aa82aa346a29e7cb51cda3a405
https://github.com/pycasbin/pymongo-adapter/pull/10

**Comment by hsluoyz** [comment]
@Nekotoxin

**Comment by Nekotoxin** [comment]
> @Nekotoxin

ok
