### ISSUE TITLE
initialize_enforcer with other DB_ALIAS 

### ISSUE THREAD

**Issue by hefeiyun** [pycasbin/django-orm-adapter#18]
if django database config in `backend/settings.py` like:
---
DATABASES = {
    'default': {...},
    'acount': {...},
}
---
and we want use `account` db to store casbin_rule, HOW?

**Comment by BustDot** [comment]
The django [docs](https://docs.djangoproject.com/en/4.2/topics/db/multi-db/#:~:text=Use%20the%20using%20keyword%20to,the%20data%20should%20be%20saved.&text=If%20you%20don%27t%20specify,database%20allocated%20by%20the%20routers.) illustrate how to use another databases.

Since the django-orm-adapter uses the default databases, you can add a database argument for the adapter and change the code whenever interacting with the django-orm.

For example(I'm not sure whether it is correct, just for demonstration):
```python
def save_policy(self, model):
        """saves all policy rules to the storage."""
        # See https://casbin.org/docs/en/adapters#autosave
        # for why this is deleting all rules
        CasbinRule.objects.using("account").all().delete()

        lines = []
        for sec in ["p", "g"]:
            if sec not in model.model.keys():
                continue
            for ptype, ast in model.model[sec].items():
                for rule in ast.policy:
                    lines.append(self._create_policy_line(ptype, rule))
        CasbinRule.objects.using("account").bulk_create(lines)
        return True
```

**Comment by hefeiyun** [comment]
> The django [docs](https://docs.djangoproject.com/en/4.2/topics/db/multi-db/#:~:text=Use%20the%20using%20keyword%20to,the%20data%20should%20be%20saved.&text=If%20you%20don%27t%20specify,database%20allocated%20by%20the%20routers.) illustrate how to use another databases.
> 
> Since the django-orm-adapter uses the default databases, you can add a database argument for the adapter and change the code whenever interacting with the django-orm.
> 
> For example(I'm not sure whether it is correct, just for demonstration):
> 
> ```python
> def save_policy(self, model):
>         """saves all policy rules to the storage."""
>         # See https://casbin.org/docs/en/adapters#autosave
>         # for why this is deleting all rules
>         CasbinRule.objects.using("account").all().delete()
> 
>         lines = []
>         for sec in ["p", "g"]:
>             if sec not in model.model.keys():
>                 continue
>             for ptype, ast in model.model[sec].items():
>                 for rule in ast.policy:
>                     lines.append(self._create_policy_line(ptype, rule))
>         CasbinRule.objects.using("account").bulk_create(lines)
>         return True
> ```


NOT save, but how to initialize_enforcer() with other DB_ALIAS: 
https://github.com/pycasbin/django-orm-adapter/blob/master/casbin_adapter/enforcer.py

**Comment by hsluoyz** [comment]
@BustDot the DB name should be customizable in the constructor function, this feature should be supported. See other adapter as example: https://github.com/pycasbin/pymongo-adapter#simple-example

![image](https://github.com/pycasbin/django-orm-adapter/assets/3787410/774439dc-e0dc-4aae-a874-9a93f6de4c4a)

**Comment by BustDot** [comment]
> @BustDot the DB name should be customizable in the constructor function, this feature should be supported. See other adapter as example: https://github.com/pycasbin/pymongo-adapter#simple-example
> 
> ![image](https://user-images.githubusercontent.com/3787410/257097663-774439dc-e0dc-4aae-a874-9a93f6de4c4a.png)

I will look into it.

**Comment by hefeiyun** [comment]
> > @BustDot the DB name should be customizable in the constructor function, this feature should be supported. See other adapter as example: https://github.com/pycasbin/pymongo-adapter#simple-example
> > ![image](https://user-images.githubusercontent.com/3787410/257097663-774439dc-e0dc-4aae-a874-9a93f6de4c4a.png)
> 
> I will look into it.

It's better be configurable, i think.

**Comment by hefeiyun** [comment]
still error

initialize_enforcer() first called here:
https://github.com/pycasbin/django-orm-adapter/blob/master/casbin_adapter/apps.py
