### ISSUE TITLE
CASBIN_LOG_ENABLED not working

### ISSUE THREAD

**Issue by leohahn** [pycasbin/django-orm-adapter#19]
Adding 
```python
CASBIN_LOG_ENABLED = False
```

does not work. Looking into the code the setting is not passed to the constructor. That seems to be a bug right?

**Comment by hsluoyz** [comment]
@leohahn it's here:

https://github.com/pycasbin/django-orm-adapter/blob/9cc651366706058502da217a87f97f91fe3fcd6c/casbin_adapter/enforcer.py#L28

**Comment by leohahn** [comment]
Yes, but this variable is not used anywhere. I tried setting this to true but nothing changes for logging. Where is this variable used?

**Comment by hsluoyz** [comment]
@BustDot

**Comment by BustDot** [comment]
@leohahn 
You can control the log by setting logging config in settings.py. You can refer to django [docs](https://docs.djangoproject.com/en/4.2/topics/logging/).
Here is an example to log info and upper level message to console:
```python
# settings.py
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "casbin_formatter": {
            "format": "{asctime} {message}",
            "style": "{",
        }
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "casbin_formatter",
        },
    },
    "loggers": {
        "casbin_adapter": {
            "handlers": ["console"],
            "level": "INFO",
        },
    },
}
```
