### ISSUE TITLE
bug: CASBIN_DB_ALIAS not work

### ISSUE THREAD

**Issue by hefeiyun** [pycasbin/django-orm-adapter#22]
initialize_enforcer() first called here:
https://github.com/pycasbin/django-orm-adapter/blob/master/casbin_adapter/apps.py
---
so CASBIN_DB_ALIAS not work

**Comment by BustDot** [comment]
> ## initialize_enforcer() first called here:
> https://github.com/pycasbin/django-orm-adapter/blob/master/casbin_adapter/apps.py
> so CASBIN_DB_ALIAS not work

I am not familiar with django middlewares. Can you provide some information about how django middleware works or how does it initialize?

**Comment by hefeiyun** [comment]
> 



> > ## initialize_enforcer() first called here:
> > https://github.com/pycasbin/django-orm-adapter/blob/master/casbin_adapter/apps.py
> > so CASBIN_DB_ALIAS not work
> 
> I am not familiar with django middlewares. Can you provide some information about how django middleware works or how does it initialize?

ready() is called when it initialize:
https://github.com/pycasbin/django-orm-adapter/blob/master/casbin_adapter/apps.py
--
so make sure CASBIN_DB_ALIAS  work at ready() in `casbin_adapter/apps.py`

**Comment by hefeiyun** [comment]
@BustDot you can read this
https://github.com/pycasbin/django-orm-adapter/pull/23/commits
