### ISSUE TITLE
`semantic-release-pypi@^3.0.0` uses the `pyproject.toml` based build system interface, if a `pyproject.toml` file exists

### ISSUE THREAD

**Issue by abichinger** [pycasbin/django-orm-adapter#26]
This project uses `setup.py` to build and `pyproject.toml` only for linting.

This will cause the release workflow to fail with the following error:
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/node/18.18.2/x64/lib/node_modules/semantic-release-pypi/dist/py/set_version.py", line 24, in <module>
    toml['project']['version'] = args.version
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/tomlkit/container.py", line 613, in __getitem__
    raise NonExistentKey(key)
tomlkit.exceptions.NonExistentKey: 'Key "project" does not exist.'
```

The PyPA recommends to migrate away from `setup.py` ([Build System Interface](https://pip.pypa.io/en/stable/reference/build-system/#))

Related:
- https://github.com/abichinger/semantic-release-pypi/issues/31
- https://github.com/casbin/pycasbin/pull/331
- https://github.com/casbin/pycasbin/pull/332

Projects that are also affected:
- https://github.com/pycasbin/django-authorization
- https://github.com/pycasbin/redis-watcher
- https://github.com/pycasbin/etcd-watcher

**Comment by hsluoyz** [comment]
@abichinger hi, can you make a PR?

**Comment by abichinger** [comment]
Hi, I'm going to make a PR in the next few days
