### ISSUE TITLE
Fix the Travis CI build error

### ISSUE THREAD

**Issue by hsluoyz** [pycasbin/django-orm-adapter#3]
See: https://www.travis-ci.org/github/pycasbin/django-orm-adapter

![image](https://user-images.githubusercontent.com/3787410/80984162-16475680-8e60-11ea-91bc-c2ff388c0b29.png)

**Comment by hsluoyz** [comment]
Can anyone work on this? @techoner @nodece @DivyPatel9881

**Comment by divy9881** [comment]
Okay, I will look into this.

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/pycasbin/django-orm-adapter/pull/2
