### ISSUE TITLE
in pypi i can't find this package, this repo has another name?

### ISSUE THREAD

**Issue by LiuG-lynx** [pycasbin/django-orm-adapter#5]

**Comment by hsluoyz** [comment]
Can any one fix the CI and submit to pypi?

@techoner @nodece @poetL @DivyPatel9881 @hackerchai @kingiw

**Comment by LiuG-lynx** [comment]
I'd like to give it a try, but I'm not sure if I have permission to commit to pypi @hsluoyz

**Comment by hsluoyz** [comment]
You can fix CI and setup the config for pypi. I will do the final submit.

**Comment by LiuG-lynx** [comment]
I used my own account for the test. The original CI and setup.py of the repository are running normally. Please submit them to pypi @hsluoyz

**Comment by hsluoyz** [comment]
@poetL please refine setup.py based on: https://github.com/casbin/pycasbin/blob/master/setup.py

**Comment by hsluoyz** [comment]
PR: https://github.com/pycasbin/django-orm-adapter/pull/7

**Comment by hsluoyz** [comment]
0.0.1 released in pypi: https://github.com/pycasbin/django-orm-adapter
